### ISSUE TITLE
Error with info Method for Certain Packages

### ISSUE THREAD

**Issue by c4uran** [karpierz/chocolatey#1]
### **Issue Description**

Encountered an issue with the info method in the Chocolatey class, specifically when retrieving information for certain packages, like dotnet-7.0-desktopruntime.

### **Steps to Reproduce**

    Call the info method with pkg_id set to dotnet-7.0-desktopruntime.
    Observe that an error is thrown.

### **Expected Behavior**

The method should return package information without any errors.

### **Actual Behavior**

The method fails and returns an error for specific package IDs.

### **Modified Method**

I've made some modifications to the info method to handle this issue:
```
def info(self, *, pkg_id: str, local_only=False, **kwargs) -> Optional[PackageInfo]:
    """Retrieves package information."""
    self._omit_args(kwargs, "limit_output", "verbose")
    try:
        output = self.cmd.info(pkg_id, limit_output=True, local_only=local_only, **self._capture_output, **kwargs)
    except run.CalledProcessError as exc:
        self._handle_exception(exc)
        return None  # Return None if an error occurred

    if not output.stdout.strip():
        return None  # Return None if the output is empty

    # Processing the command output
    packages = self._packages(output.stdout, klass=PackageInfo)
    if not packages:
        return None  # Return None if no packages are found

    pkg_info = list(packages.values())[0]
    return pkg_info  # Return information about the first found package

```

### **Additional Information**

This modification seems more like a workaround, but it resolved the issue I was facing.

**Comment by karpierz** [comment]
Fixed in https://github.com/karpierz/chocolatey/releases/tag/0.3.1
